<!DOCTYPE html>
<html>
	<head>
		<title>
			[page]
		</title>
		<link rel='icon' type ='image/x-icon' href='[mypath]/images/easy_as_python.ico'>
		<link rel = "stylesheet" href = "[mypath]/css/stylesheet.css?v=[cart]">
		[showif [grade]=1]<link rel="stylesheet" href="[mypath]/css/grade_nav.css?v=[cart]">[/showif]
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>

	<body>
		<hr>
		<div class ='heading'>
			<br>
			<h1 id = "heading_text">
				[page]
			</h1>
			<br>
		</div>
		<br>
		<hr>
